// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import Providers from './providers'
import Navbar from './components/Navbar'
import Head from 'next/head'

const inter = Outfit({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'InvestiTrack',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Head>
        <link rel="icon" href="/stock.png" type="image/png" />
      </Head>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
